name: Publish and Deploy Dotnet Plugins

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Find csproj files and publish them
      run: |
        csproj_files=$(find src/plugins -name "*.csproj")
        for csproj in $csproj_files; do
          project_name=$(basename "$csproj" .csproj)
          mkdir -p "Plugins/$project_name"
          dotnet publish "$csproj" -o "Plugins/$project_name"
        done
        
    - name: Create zip file
      run: zip -r plugins.zip Plugins

    - name: Push to DigitalOcean
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.DO_ACCESS_KEY}}
        secret_key: ${{ secrets.DO_SECRET_KEY }}
        space_name: ${{ secrets.DO_SPACE_NAME }}
        space_region: ${{ secrets.DO_SPACE_REGION }}
        source: ./plugins.zip
        out_dir: dc-web/${{ steps.version.outputs.full_without_prefix }}
