name: Create Plugins
on:
  workflow_call:
jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.prepare.outputs.matrix }}
    steps:
    -  uses: actions/checkout@master
    -  run: |
        matrix=$(git ls-tree -r HEAD | find src/plugins -name "*.csproj" | git ls-tree -r --name-only | awk -v FS="," '{print $1}')
        echo "Matrix: $matrix"
        echo "::set-output name=matrix::$matrix"
  create:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@master
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Adding NuGet Registries
        run: |
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --configfile ./nuget.config --name github_pipeline --username ${{ secrets.DSSL_USERNAME }} --password ${{  secrets.DSSL_TOKEN }}  --store-password-in-clear-text
          dotnet nuget add source https://api.nuget.org/v3/index.json --configfile ./nuget.config --name nuget_pipeline
      - name: "Navigate to Workspace"
        run: cd ${{ github.workspace }}
      - name: Create Directories
        run: mkdir _build
      - name: Build
        run: dotnet publish src/plugins/${{ needs.prepare.outputs.matrix }}/${{ needs.prepare.outputs.matrix }}.csproj --output ./build --verbosity q -c Release
      - name: "Archive Plugin"
        uses: actions/upload-artifact@v3
        with:
           name: ${{ needs.prepare.outputs.matrix }}
           path: _build/${{ needs.prepare.outputs.matrix }}
  upload: 
    runs-on: ubuntu-latest
    needs: create
    steps:
      - name: Get DLLs
        uses: actions/download-artifact@v3
      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          file_path: plugins.zip
      - name: Push to DigitalOcean
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY}}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: plugins.zip
          out_dir: dc-web/${{ steps.version.outputs.full_without_prefix }}
