name: 'Create packages'
on:
  workflow_call:
    inputs:
      event-ref:  
        description: 'github.event.ref'
        required: true
        type: string
      ref-name:  
        description: 'github.ref_name'
        required: true
        type: string
      ref-cache-key:  
        description: 'cache-key'
        required: true
        type: string
      user-trigger:  
        description: 'action-trigger-user'
        required: true
        type: string

jobs:
  variables:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      alpha-release: ${{ steps.alpha.outputs.version }}
    steps:
      - id: alpha
        run: echo "version=$(date +'%-H%M%S')" >> $GITHUB_OUTPUT
  create:
    needs: variables
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x 
          
      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --username ${{ inputs.ref-cache-key }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
        
      - name: Restore dependencies
        run: dotnet restore --no-cache --force
      
      - name: Build
        run: dotnet build --no-restore
        
      - name: Create live Package
        run: dotnet pack --configuration Release
        if: startsWith(inputs.event-ref, 'refs/tags/v')
          
      - name: Create alpha Package
        run: |
          echo "alpha.${{ needs.variables.outputs.alpha-release }}"
          dotnet pack --configuration Release --version-suffix "alpha.${{ needs.variables.outputs.alpha-release }}"
        if: startsWith(inputs.event-ref, 'refs/tags/v') != true
      
      - name: Copy files for cache
        run: |
          mkdir -p ${{ github.workspace }}/cache
          find . -type f -name "*.nupkg" -exec cp {} ${{ github.workspace }}/cache \;
          cp nuget.config ${{ github.workspace }}/cache
          
      - name: Cache
        uses: actions/cache@v3        
        with:        
         path: ${{ github.workspace }}/cache
         key: ${{ inputs.ref-cache-key }}      
        
  publish:
    runs-on: ubuntu-latest
    needs: create
    steps:   
    
     - name: Setup .NET
       uses: actions/setup-dotnet@v3
       with:
         dotnet-version: 6.0.x
         
     - name: Restore
       uses: actions/cache@v3
       with:
         path: ${{ github.workspace }}/cache
         key: ${{ inputs.ref-cache-key }}    
          
     - name: Delete release packages
       uses: Digital-Secure-Systems-Limited/CI-Actions-DeleteRepoPackageVersion@main
       id: delete-nuget
       with:
          package-token: ${{ github.token }}
          package-version: ${{ github.ref_name }}
       if: startsWith(inputs.event-ref, 'refs/tags/v')
               
     - name: Publish
       run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}" --skip-duplicate -n
