name: Publish and Deploy Dotnet Plugins

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_CONFIG_PATH: ./nuget.config
    steps:
    - uses: nowsprinting/check-version-format-action@v3
      id: version
      with:
        prefix: 'v'
        
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x 
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
          
    - name: Add Sources to NuGet
      run: |
         dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github_pipeline --username ${{  secrets.DSSL_USERNAME }} --password ${{  secrets.DSSL_TOKEN }}  --store-password-in-clear-text
      
    - name: Restore dependencies
      run: dotnet restore --no-cache --force
    
    - name: Find csproj files and publish them
      run: |
        csproj_files=$(find src/plugins -name "*.csproj")
        for csproj in $csproj_files; do
          project_name=$(basename "$csproj" .csproj)
          mkdir -p "PaymentPlugins/$project_name"
          dotnet publish "$csproj" -o "PaymentPlugins/$project_name" 
        done
        
    - name: Create zip file
      run: zip -r plugins.zip PaymentPlugins

    - name: Push to DigitalOcean
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.DO_ACCESS_KEY}}
        secret_key: ${{ secrets.DO_SECRET_KEY }}
        space_name: ${{ secrets.DO_SPACE_NAME }}
        space_region: ${{ secrets.DO_SPACE_REGION }}
        source: plugins.zip
        out_dir: dc-web/${{ steps.version.outputs.full_without_prefix }}
