name: Publish and Deploy Dotnet Plugins

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - uses: actions/checkout@v2

      - name: Create a new directory
        run: mkdir build

      - name: List directories
        run: ls -dR */

      - name: List project files
        run: dotnet list -v normal --path ./src/plugins | grep "Project" | awk '{print $2}' > projects.txt

      - name: Publish each project
        run: |
          for project in $(cat projects.txt); do
          dotnet publish $project -o ./build/plugins/$project
          done

      - name: Zip plugins folder
        run: zip -r plugins.zip ./build/plugins

      - name: Push to DigitalOcean
        uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY}}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: ./plugins.zip
          out_dir: dc-web/${{ steps.version.outputs.full_without_prefix }}
