name: Publish and Deploy Dotnet Plugins

on:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_CONFIG_PATH: /nuget.config
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x 
    
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.1.1
          
    - name: Add Sources to NuGet
      run: |
          nuget sources add -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -configfile ./nuget.config -name github_pipeline -username ${{  secrets.DSSL_USERNAME }} -password ${{ secrets.DSSL_TOKEN }} -StorePasswordInClearText
          nuget sources add -source https://api.nuget.org/v3/index.json -configfile ./nuget.config -name nuget_pipeline
    
    - name: Find csproj files and publish them
      run: |
        csproj_files=$(find src/plugins -name "*.csproj")
        for csproj in $csproj_files; do
          project_name=$(basename "$csproj" .csproj)
          mkdir -p "Plugins/$project_name"
          dotnet publish "$csproj" -o "Plugins/$project_name" 
        done
        
    - name: Create zip file
      run: zip -r plugins.zip Plugins

    - name: Push to DigitalOcean
      uses: BetaHuhn/do-spaces-action@v2
      with:
        access_key: ${{ secrets.DO_ACCESS_KEY}}
        secret_key: ${{ secrets.DO_SECRET_KEY }}
        space_name: ${{ secrets.DO_SPACE_NAME }}
        space_region: ${{ secrets.DO_SPACE_REGION }}
        source: ./plugins.zip
        out_dir: dc-web/${{ steps.version.outputs.full_without_prefix }}
