name: 'Create packages'
on:
  workflow_call:
    inputs:
      event-ref:  
        description: 'github.event.ref'
        required: true
        type: string
      ref-name:  
        description: 'github.ref_name'
        required: true
        type: string
      ref-cache-key:  
        description: 'cache-key'
        required: true
        type: string
jobs:
  variables:
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      alpha-release: ${{ steps.alpha.outputs.version }}
    steps:
      - id: alpha
        run: echo "version=$(date +'%-H%M%S')" >> $GITHUB_OUTPUT
        
       
  create:
    needs: variables
    runs-on: ubuntu-latest
    steps:     
      - uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x 
          
      - name: Add private GitHub registry to NuGet
        run: dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --name github_pipeline --username ${{  secrets.DSSL_USERNAME }} --password ${{  secrets.DSSL_TOKEN }}  --store-password-in-clear-text
        
      - name: Get folders in src
        id: packagenames
        run: |
          packages=`ls -m ${{ github.workspace }}/src/`
          packages=$(echo $packages | tr '\n' ' ')
          echo "package_names=$packages" >> $GITHUB_OUTPUT
          
      - name: Restore dependencies
        run: dotnet restore --no-cache --force
      
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
          
      - name: Set version number
        run: sed -i 's/<Version>\(.*\)<\/Version>/<Version>${{ steps.version.outputs.full_without_prefix }}<\/Version>/' ${{ github.workspace }}/src/*/*.csproj   
          
      - name: Build
        run: dotnet build --no-restore
               
      - name: Create package
        run: dotnet pack -p:IncludeSymbols=true -p:SymbolPackageFormat=snupkg --configuration Release
         
      - name: Delete release packages
        uses: Digital-Secure-Systems-Limited/CI-Actions-DeleteRepoPackageVersion@main
        id: delete-nuget
        with:
          package-token: ${{ secrets.DSSL_TOKEN }}
          package-version: ${{ github.ref_name }}
          package-names: ${{ steps.packagenames.outputs.package_names }}
          
      - name: Publish package
        run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}" --skip-duplicate
      
      - name: Publish debug package
        run: dotnet nuget push "**/*.snupkg" --api-key ${{ secrets.GITHUB_TOKEN }} --source "https://nuget.pkg.github.com/${{ github.repository_owner }}" --skip-duplicate


   
        
