name: 'Run SonarCloud'
on:
  workflow_call:
    inputs:
      sonarProjectKey:  
        description: 'Project key'
        required: true
        type: string
      sonarProjectName:  
        description: 'project name'
        required: true
        type: string
      projectFile:  
        description: 'project file'
        required: false
        type: string
      testProjectFile:  
        description: 'test project file'
        required: false
        type: string
        default: ''
      projectFolder:  
        description: 'project folder'
        required: true
        type: string
     
env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze:
    name: Analyze
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x

    - uses: actions/cache@v3
      with:
        path: .nuget/packages
        key: ${{ runner.os }}-nuget
        restore-keys: |
          ${{ runner.os }}-nuget
     
    - name: SonarScanner for .NET 6 with pull request decoration support
      uses: highbyte/sonarscan-dotnet@v2.2.4
      with:
        sonarProjectKey: ${{ inputs.sonarProjectKey }} 
        sonarProjectName: ${{ inputs.sonarProjectName }}
        sonarOrganization: dssl
        # Optional command arguments to dotnet test
        # Optional extra command arguments the the SonarScanner 'begin' command
        dotnetBuildArguments: ${{ inputs.projectFile }} --source .nuget/packages
        dotnetDisableTests: ${{ inputs.testProjectFile == ''}} 
        dotnetTestArguments: ${{ inputs.testProjectFile }} --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.src="/github/workspace/src" /d:sonar.test="/test" /d:sonar.projectBaseDir="/github/workspace/src/${{ inputs.projectFolder }}" /d:sonar.exclusions="**/Migrations/**/*,**/wwwroot/**/*,**/*Module.cs,**/*.xml,**/*.lic" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

