name: 'Run SonarCloud'
on:
  workflow_call:
    inputs:
      sonarProjectKey:  
        description: 'Project key'
        required: true
        type: string
      sonarProjectName:  
        description: 'project name'
        required: true
        type: string
      projectFile:  
        description: 'project file'
        required: false
        type: string
      testProjectFile:  
        description: 'test project file'
        required: false
        type: string
        default: ''
      projectFolder:  
        description: 'project folder'
        required: true
        type: string
     
env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  analyze:
    timeout-minutes: 10
    name: Analyze
    runs-on: self-hosted
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      if: ${{ inputs.testProjectFile != ''}} 
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.x 

    - name: Add NuGet package source
      if: ${{ inputs.testProjectFile != ''}} 
      uses: deitry/add-nuget-source-action@v1.0.1
      with:
        url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        username: ${{  secrets.DSSL_USERNAME }}
        password: ${{  secrets.DSSL_TOKEN }}

    - name: Tests
      if: ${{ inputs.testProjectFile != ''}} 
      run: |
        dotnet test ${{ inputs.testProjectFile }} --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
    
    - name: SonarScanner
      uses: highbyte/sonarscan-dotnet@v2.2.4
      with:
        sonarProjectKey: ${{ inputs.sonarProjectKey }} 
        sonarProjectName: ${{ inputs.sonarProjectName }}
        sonarOrganization: dssl
        dotnetBuildArguments: ${{ inputs.projectFile }}
        dotnetPreBuildCmd: |
          dotnet nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --configfile ./nuget.config --name github_pipeline --username ${{  secrets.DSSL_USERNAME }} --password ${{  secrets.DSSL_TOKEN }}  --store-password-in-clear-text
        dotnetDisableTests: true #${{ inputs.testProjectFile == ''}} 
        dotnetTestArguments: ${{ inputs.testProjectFile }} --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
        sonarBeginArguments: /d:sonar.src="/github/workspace/src" /d:sonar.test="/test" /d:sonar.projectBaseDir="/github/workspace/src/${{ inputs.projectFolder }}" /d:sonar.exclusions="*/Migrations/**/*,**/wwwroot/**/*,**/*Module.cs,**/*.xml,**/*.lic" /d:sonar.cs.opencover.reportsPaths="**/TestResults/**/coverage.opencover.xml" -d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx"

