name: Windows Publish
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:  
    workflow_call:
        inputs:
         zip-name:  
            description: 'Output zip file name'
            required: true
            type: string
         project-name:  
            description: 'csproj name'
            required: true
            type: string        
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'

      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Output Env Variables
        run: |
          echo $GITHUB_WORKSPACE
          echo ${{ github.workspace }}
