name: Windows Publish
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      zip-name:  
        description: 'Output zip file name'
        required: true
        type: string
      project-name:  
        description: 'csproj name'
        required: true
        type: string        
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
          
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.3

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.1.1
          
      - name: Add Sources to NuGet
        run: |
          nuget sources add -source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json -configfile ./nuget.config -name github_pipeline -username ${{  secrets.DSSL_USERNAME }} -password ${{ secrets.DSSL_TOKEN }} -StorePasswordInClearText
          nuget sources add -source https://api.nuget.org/v3/index.json -configfile ./nuget.config -name nuget_pipeline
      
      - name: Navigate to Workspace
        run: cd ${{ github.workspace }}

      - name: Create Build Directory
        run: mkdir _build
                  
      - name: Restore Packages
        run: nuget restore ${{ inputs.project-name }}.sln
        
      - name: Build
        run:  msbuild ${{ inputs.project-name }}.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build" /p:outdir="../_build" /p:version="${{ steps.version.outputs.full_without_prefix }}" -m
        
      - name: Create zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: _build
          file_path: de.zip
          verbose: 'true'
          
      - uses: BetaHuhn/do-spaces-action@v2
        with:
          access_key: ${{ secrets.DO_ACCESS_KEY}}
          secret_key: ${{ secrets.DO_SECRET_KEY }}
          space_name: ${{ secrets.DO_SPACE_NAME }}
          space_region: ${{ secrets.DO_SPACE_REGION }}
          source: ${{ inputs.zip-name }}.zip
          out_dir: dc-web/${{ steps.version.outputs.full_without_prefix }}
