name: Windows Publish
# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  workflow_call:
    inputs:
      zip-name:  
        description: 'Output zip file name'
        required: true
        type: string
      project-name:  
        description: 'csproj name'
        required: true
        type: string        
jobs:
  build:
    runs-on: windows-2019
    steps:
      - uses: nowsprinting/check-version-format-action@v3
        id: version
        with:
          prefix: 'v'
          
      - name: Checkout Repository
        uses: actions/checkout@v2
      
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.2
          
      - name: Add Sources to NuGet
        run: |
          nuget add source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json --configfile ./nuget.config --name github_pipeline --username ${{  secrets.DSSL_USERNAME }} --password ${{  secrets.DSSL_TOKEN }}  --store-password-in-clear-text
          nuget add source https://api.nuget.org/v3/index.json --configfile ./nuget.config --name nuget_pipeline
      
      - name: Navigate to Workspace
        run: cd $GITHUB_WORKSPACE

      - name: Create Build Directory
        run: mkdir _build
      
      - name: Restore Packages
        run: nuget restore ${{ inputs.project-name }}.sln

      - name: Build
        run:  msbuild ${{ inputs.project-name }}.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build" /p:version=${{ inputs.zip-name }}
